const express = require('express');
const path = require('path');
const mysql = require('mysql2/promise');
const app = express();
const PORT = process.env.PORT || 8080;

app.use(express.json());
app.use(express.static(path.join(__dirname, 'frontend', 'public')));
app.use('/src', express.static(path.join(__dirname, 'frontend', 'src')));

const pool = mysql.createPool({
    host: process.env.MYSQLHOST || 'localhost',
    user: process.env.MYSQLUSER || 'root',
    password: process.env.MYSQLPASSWORD || '',
    database: process.env.MYSQLDATABASE || 'talaen_hardware',
    port: process.env.MYSQLPORT || 3306,
    waitForConnections: true,
    connectionLimit: 10
});

async function initDB() {
    const tables = [
        `CREATE TABLE IF NOT EXISTS products (id INT AUTO_INCREMENT PRIMARY KEY, sku VARCHAR(50), name VARCHAR(255), brand VARCHAR(255) DEFAULT '', variant VARCHAR(255) DEFAULT '', category VARCHAR(255) DEFAULT 'General', price DECIMAL(10,2), cost DECIMAL(10,2) DEFAULT 0, stock INT DEFAULT 0, unit VARCHAR(50) DEFAULT 'pcs', minStock INT DEFAULT 10, isActive INT DEFAULT 1)`,
        `CREATE TABLE IF NOT EXISTS sales (id INT AUTO_INCREMENT PRIMARY KEY, receiptNo VARCHAR(50), customerName VARCHAR(255), paymentMethod VARCHAR(50), subtotal DECIMAL(10,2), tax DECIMAL(10,2), discount DECIMAL(10,2) DEFAULT 0, total DECIMAL(10,2), transportCost DECIMAL(10,2) DEFAULT 0, cashierId INT, cashierName VARCHAR(255), mpesaRef VARCHAR(100), isCredit INT DEFAULT 0, customerId INT, debtPaid DECIMAL(10,2) DEFAULT 0, date TEXT, isVoid INT DEFAULT 0, is_returned TINYINT DEFAULT 0, return_type VARCHAR(20) NULL, return_date DATETIME NULL)`,
        `CREATE TABLE IF NOT EXISTS sale_items (id INT AUTO_INCREMENT PRIMARY KEY, saleId INT, productId INT, productName VARCHAR(255), quantity INT, price DECIMAL(10,2), total DECIMAL(10,2))`,
        `CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) UNIQUE, password VARCHAR(255), role VARCHAR(50) DEFAULT 'cashier', fullName VARCHAR(255) DEFAULT '', isActive INT DEFAULT 1)`,
        `CREATE TABLE IF NOT EXISTS settings (id INT PRIMARY KEY DEFAULT 1, adminPassword VARCHAR(255) DEFAULT 'admin123', taxRate DECIMAL(10,2) DEFAULT 16, announcement TEXT DEFAULT '')`,
        `CREATE TABLE IF NOT EXISTS activity_log (id INT AUTO_INCREMENT PRIMARY KEY, userId INT, userName VARCHAR(255), action VARCHAR(100), details TEXT, date TEXT)`,
        `CREATE TABLE IF NOT EXISTS purchase_orders (id INT AUTO_INCREMENT PRIMARY KEY, poNumber VARCHAR(50), supplierName VARCHAR(255), supplierId INT, status VARCHAR(50) DEFAULT 'pending', notes TEXT, total DECIMAL(10,2) DEFAULT 0, createdBy VARCHAR(255), date TEXT, receivedDate TEXT)`,
        `CREATE TABLE IF NOT EXISTS po_items (id INT AUTO_INCREMENT PRIMARY KEY, poId INT, productName VARCHAR(255), brand VARCHAR(255), variant VARCHAR(255), quantity INT, unitPrice DECIMAL(10,2), sellingPrice DECIMAL(10,2) DEFAULT 0, lastPrice DECIMAL(10,2) DEFAULT 0, currentStock INT DEFAULT 0, discount DECIMAL(10,2) DEFAULT 0, total DECIMAL(10,2))`,
        `CREATE TABLE IF NOT EXISTS suppliers (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), contact VARCHAR(255), email VARCHAR(255), phone VARCHAR(50), address TEXT)`,
        `CREATE TABLE IF NOT EXISTS daily_reports (id INT AUTO_INCREMENT PRIMARY KEY, reportDate VARCHAR(50) UNIQUE, totalSales DECIMAL(10,2), transactionCount INT, totalItemsSold INT, closingStock INT, stockAdded INT, stockSold INT, productsCount INT)`,
        `CREATE TABLE IF NOT EXISTS mpesa_config (id INT PRIMARY KEY DEFAULT 1, consumerKey VARCHAR(255), consumerSecret VARCHAR(255), passkey VARCHAR(255), tillNumber VARCHAR(50), shortCode VARCHAR(50), environment VARCHAR(50) DEFAULT 'sandbox')`,
        `CREATE TABLE IF NOT EXISTS mpesa_transactions (id INT AUTO_INCREMENT PRIMARY KEY, transactionType VARCHAR(50), saleId INT, phoneNumber VARCHAR(50), amount DECIMAL(10,2), accountReference VARCHAR(100), checkoutRequestID VARCHAR(100), merchantRequestID VARCHAR(100), resultCode INT, resultDesc TEXT, mpesaReceiptNumber VARCHAR(50), status VARCHAR(50) DEFAULT 'pending', date TEXT)`,
        `CREATE TABLE IF NOT EXISTS credit_customers (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), phone VARCHAR(50), idNumber VARCHAR(50), address TEXT, debtLimit DECIMAL(10,2) DEFAULT 5000, totalDebt DECIMAL(10,2) DEFAULT 0, registeredBy VARCHAR(255), registeredById INT, dateRegistered TEXT, isActive INT DEFAULT 1)`,
        `CREATE TABLE IF NOT EXISTS debt_payments (id INT AUTO_INCREMENT PRIMARY KEY, customerId INT, customerName VARCHAR(255), amount DECIMAL(10,2), paymentMethod VARCHAR(50) DEFAULT 'cash', saleId INT, receivedBy VARCHAR(255), receivedById INT, date TEXT)`,
        `CREATE TABLE IF NOT EXISTS credit_sales (id INT AUTO_INCREMENT PRIMARY KEY, saleId INT, customerId INT, customerName VARCHAR(255), amount DECIMAL(10,2), debtBefore DECIMAL(10,2), debtAfter DECIMAL(10,2), cashierId INT, cashierName VARCHAR(255), date TEXT)`,
        `CREATE TABLE IF NOT EXISTS returns_table (id INT AUTO_INCREMENT PRIMARY KEY, originalSaleId INT, originalReceiptNo VARCHAR(50), customerName VARCHAR(255), returnType VARCHAR(50) DEFAULT 'return', productId INT, productName VARCHAR(255), quantity INT, returnAmount DECIMAL(10,2), exchangeProductId INT, exchangeProductName VARCHAR(255), exchangeAmount DECIMAL(10,2), refundAmount DECIMAL(10,2), reason TEXT, cashierName VARCHAR(255), date TEXT)`
    ];
    for (const table of tables) { await pool.query(table); }
    try { await pool.query("ALTER TABLE sales ADD COLUMN transportCost DECIMAL(10,2) DEFAULT 0"); } catch(e) {}
    try { await pool.query("ALTER TABLE sales ADD COLUMN is_returned TINYINT DEFAULT 0"); } catch(e) {}
    try { await pool.query("ALTER TABLE sales ADD COLUMN return_type VARCHAR(20) NULL"); } catch(e) {}
    try { await pool.query("ALTER TABLE sales ADD COLUMN return_date DATETIME NULL"); } catch(e) {}
    try { await pool.query("ALTER TABLE settings ADD COLUMN announcement TEXT DEFAULT ''"); } catch(e) {}

    const [users] = await pool.query("SELECT COUNT(*) as c FROM users");
    if (users[0].c === 0) {
        await pool.query("INSERT INTO users VALUES (1,'admin','admin123','admin','Administrator',1)");
        await pool.query("INSERT INTO users VALUES (2,'cashier','cashier123','cashier','Cashier User',1)");
        await pool.query("INSERT IGNORE INTO settings VALUES (1,'admin123',16,'')");
    }
    const [mpesa] = await pool.query("SELECT COUNT(*) as c FROM mpesa_config");
    if (mpesa[0].c === 0) { await pool.query("INSERT INTO mpesa_config (id, environment) VALUES (1, 'sandbox')"); }
    console.log('✅ Database initialized (MySQL)');
}

function logActivity(userId, userName, action, details) {
    pool.query("INSERT INTO activity_log (userId, userName, action, details, date) VALUES (?,?,?,?,NOW())", [userId||null, userName||'System', action, details]);
}

// AUTH
app.post('/api/auth/login', async (req, res) => { const { username, password } = req.body; const [user] = await pool.query("SELECT * FROM users WHERE username=? AND password=? AND isActive=1", [username, password]); if (user.length > 0) { logActivity(user[0].id, user[0].fullName, 'login', 'Logged in'); return res.json({ success: true, user: { id: user[0].id, username: user[0].username, role: user[0].role, fullName: user[0].fullName } }); } res.json({ success: false, message: 'Invalid credentials' }); });

// USERS
app.get('/api/users', async (req, res) => { const [r] = await pool.query("SELECT id, username, password, role, fullName, isActive FROM users"); res.json(r); });
app.post('/api/users', async (req, res) => { const { username, password, role, fullName } = req.body; try { const [r] = await pool.query("INSERT INTO users (username, password, role, fullName) VALUES (?,?,?,?)", [username, password, role||'cashier', fullName]); logActivity(null, 'Admin', 'add_user', 'Added: ' + fullName); res.json({ success: true, id: r.insertId }); } catch(e) { res.json({ success: false, message: 'Username exists' }); } });
app.put('/api/users/:id', async (req, res) => { const { password, isActive, fullName, username, toggle } = req.body; const [user] = await pool.query("SELECT * FROM users WHERE id=?", [req.params.id]); if (!user.length) return res.json({ success: false }); if (password) { await pool.query("UPDATE users SET password=? WHERE id=?", [password, req.params.id]); } if (isActive !== undefined) await pool.query("UPDATE users SET isActive=? WHERE id=?", [isActive, req.params.id]); if (toggle) { if (user[0].role === 'admin') return res.json({ success: false, message: 'Cannot deactivate admin' }); await pool.query("UPDATE users SET isActive=? WHERE id=?", [user[0].isActive ? 0 : 1, req.params.id]); } if (fullName) await pool.query("UPDATE users SET fullName=? WHERE id=?", [fullName, req.params.id]); if (username) await pool.query("UPDATE users SET username=? WHERE id=?", [username, req.params.id]); res.json({ success: true }); });

// SETTINGS (Updated with announcement)
app.get('/api/settings', async (req, res) => { const [r] = await pool.query("SELECT * FROM settings WHERE id=1"); res.json(r[0] || { adminPassword: 'admin123' }); });
app.put('/api/settings', async (req, res) => { 
    if (req.body.adminPassword) { await pool.query("UPDATE settings SET adminPassword=? WHERE id=1", [req.body.adminPassword]); }
    if (req.body.announcement !== undefined) { await pool.query("UPDATE settings SET announcement=? WHERE id=1", [req.body.announcement]); }
    res.json({ success: true }); 
});

// ACTIVITY
app.get('/api/activity', async (req, res) => { const [r] = await pool.query("SELECT * FROM activity_log ORDER BY date DESC LIMIT 100"); res.json(r); });
app.delete('/api/activity', async (req, res) => { await pool.query("DELETE FROM activity_log"); res.json({ success: true }); });

// SUPPLIERS
app.get('/api/suppliers', async (req, res) => { const [r] = await pool.query("SELECT * FROM suppliers ORDER BY name"); res.json(r); });
app.post('/api/suppliers', async (req, res) => { const { name, phone, email, address } = req.body; const [r] = await pool.query("INSERT INTO suppliers (name, phone, email, address) VALUES (?,?,?,?)", [name, phone, email, address]); res.json({ success: true, id: r.insertId }); });

// PRODUCTS
app.get('/api/products', async (req, res) => { const [r] = await pool.query("SELECT * FROM products WHERE isActive=1 ORDER BY name,brand"); res.json(r); });
app.get('/api/products/paginated', async (req, res) => { try { var page = parseInt(req.query.page) || 1; var limit = parseInt(req.query.limit) || 25; var search = req.query.search || ''; var category = req.query.category || ''; var stockFilter = req.query.stock || ''; var offset = (page - 1) * limit; var whereClause = 'WHERE isActive = 1'; var params = []; if (search) { whereClause += ' AND (name LIKE ? OR brand LIKE ? OR variant LIKE ? OR category LIKE ?)'; var q = '%' + search + '%'; params.push(q, q, q, q); } if (category) { whereClause += ' AND category = ?'; params.push(category); } if (stockFilter === 'out') { whereClause += ' AND stock = 0'; } else if (stockFilter === 'low') { whereClause += ' AND stock > 0 AND stock <= minStock'; } else if (stockFilter === 'ok') { whereClause += ' AND stock > minStock'; } var [countResult] = await pool.query('SELECT COUNT(*) as total FROM products ' + whereClause, params); var total = countResult[0].total; params.push(limit, offset); var [products] = await pool.query('SELECT * FROM products ' + whereClause + ' ORDER BY name, brand LIMIT ? OFFSET ?', params); res.json({ products: products, pagination: { page: page, limit: limit, total: total, totalPages: Math.ceil(total / limit), hasNext: offset + limit < total, hasPrev: page > 1 } }); } catch(e) { res.json({ products: [], pagination: { page: 1, limit: 25, total: 0, totalPages: 0, hasNext: false, hasPrev: false } }); } });
app.get('/api/products/categories', async (req, res) => { try { var [categories] = await pool.query("SELECT DISTINCT category FROM products WHERE isActive = 1 AND category != '' ORDER BY category"); res.json(categories.map(function(c) { return c.category; })); } catch(e) { res.json([]); } });
app.get('/api/products/with-prices', async (req, res) => { const [products] = await pool.query("SELECT * FROM products WHERE isActive=1 ORDER BY name,brand"); for (let p of products) { const [lastPO] = await pool.query("SELECT pi.unitPrice, pi.sellingPrice FROM po_items pi JOIN purchase_orders po ON pi.poId=po.id WHERE pi.productName=? AND pi.brand=? AND pi.variant=? ORDER BY po.date DESC LIMIT 1", [p.name, p.brand, p.variant]); p.lastPrice = lastPO.length ? lastPO[0].unitPrice : p.cost; } res.json(products); });
app.post('/api/products', async (req, res) => { const { name, brand, variant, category, price, cost, stock, unit } = req.body; const sku = Date.now().toString(36).toUpperCase(); const [r] = await pool.query("INSERT INTO products (sku,name,brand,variant,category,price,cost,stock,unit) VALUES (?,?,?,?,?,?,?,?,?)", [sku, name, brand, variant, category, price, cost||0, stock||0, unit||'pcs']); logActivity(null, 'Admin', 'add_product', 'Added: ' + (brand||'') + ' ' + name); res.json({ success: true, id: r.insertId }); });
app.put('/api/products/:id', async (req, res) => { const { name, brand, variant, price, cost, stock, unit } = req.body; await pool.query("UPDATE products SET name=?,brand=?,variant=?,price=?,cost=?,stock=?,unit=? WHERE id=?", [name,brand,variant,price,cost,stock,unit,req.params.id]); res.json({ success: true }); });
app.delete('/api/products/:id', async (req, res) => { await pool.query("UPDATE products SET isActive=0 WHERE id=?", [req.params.id]); res.json({ success: true }); });
app.put('/api/products/:id/stock', async (req, res) => { await pool.query("UPDATE products SET stock=stock+? WHERE id=?", [req.body.quantity, req.params.id]); res.json({ success: true }); });
app.get('/api/products/search', async (req, res) => { const q = '%' + (req.query.q || '') + '%'; const [products] = await pool.query("SELECT id, name, brand, variant, price, stock, unit FROM products WHERE isActive=1 AND (name LIKE ? OR brand LIKE ? OR variant LIKE ?) AND stock > 0 ORDER BY name LIMIT 20", [q, q, q]); res.json(products); });

// SALES
app.get('/api/sales', async (req, res) => { const [sales] = await pool.query("SELECT * FROM sales ORDER BY date DESC"); for (let s of sales) { const [items] = await pool.query("SELECT * FROM sale_items WHERE saleId = ?", [s.id]); s.items = items; } res.json(sales); });
app.get('/api/sales/cashiers-summary', async (req, res) => { const [cashiers] = await pool.query("SELECT id, fullName, username FROM users WHERE role='cashier' AND isActive=1"); const today = new Date().toISOString().split('T')[0]; const result = []; for (let c of cashiers) { const [sales] = await pool.query("SELECT * FROM sales WHERE cashierId=? AND isVoid=0", [c.id]); const todaySales = sales.filter(s => s.date && s.date.startsWith(today)); result.push({ id: c.id, name: c.fullName, username: c.username, totalAll: sales.reduce((s, sale) => s + Number(sale.total), 0), totalToday: todaySales.reduce((s, sale) => s + Number(sale.total), 0), countAll: sales.length, countToday: todaySales.length }); } res.json(result); });
app.get('/api/sales/cashier/:id', async (req, res) => { const [sales] = await pool.query("SELECT * FROM sales WHERE cashierId=? AND isVoid=0 ORDER BY date DESC", [req.params.id]); const today = new Date().toISOString().split('T')[0]; const todaySales = sales.filter(s => s.date && s.date.startsWith(today)); res.json({ all: sales, today: todaySales, totalAll: sales.reduce((s, sale) => s + Number(sale.total), 0), totalToday: todaySales.reduce((s, sale) => s + Number(sale.total), 0), countAll: sales.length, countToday: todaySales.length }); });
app.post('/api/sales', async (req, res) => { const { customerName, items, paymentMethod, subtotal, tax, discount, total, cashierId, cashierName, mpesaRef, isCredit, customerId, debtPaid, transportCost } = req.body; const rn = 'TIH-' + Date.now().toString(36).toUpperCase(); const [s] = await pool.query("INSERT INTO sales (receiptNo,customerName,paymentMethod,subtotal,tax,discount,total,transportCost,cashierId,cashierName,mpesaRef,isCredit,customerId,debtPaid,date) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())", [rn, customerName, paymentMethod, subtotal, tax, discount||0, total, transportCost||0, cashierId||null, cashierName||null, mpesaRef||null, isCredit||0, customerId||null, debtPaid||0]); const saleId = s.insertId; for (let i of items) { await pool.query("INSERT INTO sale_items (saleId,productId,productName,quantity,price,total) VALUES (?,?,?,?,?,?)", [saleId, i.productId, i.productName, i.quantity, i.price, i.quantity*i.price]); await pool.query("UPDATE products SET stock=stock-? WHERE id=?", [i.quantity, i.productId]); } logActivity(cashierId, cashierName, 'sale', 'Sale: ' + rn + ' - KES ' + (total||0).toLocaleString()); res.json({ success: true, receiptNo: rn, saleId: saleId }); });

// RETURNS
app.post('/api/returns', async (req, res) => { const { originalSaleId, originalReceiptNo, customerName, returnType, productId, productName, quantity, returnAmount, exchangeProductId, exchangeProductName, exchangeAmount, refundAmount, reason, cashierName } = req.body; try { await pool.query("INSERT INTO returns_table (originalSaleId, originalReceiptNo, customerName, returnType, productId, productName, quantity, returnAmount, exchangeProductId, exchangeProductName, exchangeAmount, refundAmount, reason, cashierName, date) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())", [originalSaleId, originalReceiptNo, customerName, returnType, productId, productName, quantity, returnAmount, exchangeProductId||null, exchangeProductName||null, exchangeAmount||0, refundAmount||0, reason, cashierName]); await pool.query("UPDATE products SET stock = stock + ? WHERE id = ?", [quantity, productId]); if (exchangeProductId) { await pool.query("UPDATE products SET stock = stock - 1 WHERE id = ? AND stock > 0", [exchangeProductId]); } const [originalSale] = await pool.query("SELECT * FROM sales WHERE id = ?", [originalSaleId]); if (originalSale.length && originalSale[0].isCredit == 1 && originalSale[0].customerId) { await pool.query("UPDATE credit_customers SET totalDebt = GREATEST(0, totalDebt - ?) WHERE id = ?", [returnAmount, originalSale[0].customerId]); } await pool.query("UPDATE sales SET is_returned = 1, return_type = ?, return_date = NOW() WHERE id = ?", [returnType, originalSaleId]); logActivity(null, cashierName, 'return', 'Return: ' + originalReceiptNo + ' - ' + productName); res.json({ success: true }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.get('/api/returns', async (req, res) => { const [r] = await pool.query("SELECT * FROM returns_table ORDER BY date DESC LIMIT 100"); res.json(r); });
app.get('/api/returns/receipt/:receiptNo', async (req, res) => { const [returns] = await pool.query("SELECT productId, quantity, returnType, date FROM returns_table WHERE originalReceiptNo = ? ORDER BY date DESC", [req.params.receiptNo]); res.json(returns); });
app.get('/api/returns/summary', async (req, res) => { try { var [totalReturns] = await pool.query("SELECT COUNT(*) as count FROM returns_table WHERE returnType='return'"); var [totalExchanges] = await pool.query("SELECT COUNT(*) as count FROM returns_table WHERE returnType='exchange'"); var [totalRefunded] = await pool.query("SELECT SUM(refundAmount) as total FROM returns_table"); var today = new Date().toISOString().split('T')[0] + '%'; var [todayReturns] = await pool.query("SELECT COUNT(*) as count FROM returns_table WHERE date LIKE ?", [today]); res.json({ totalReturns: totalReturns[0].count || 0, totalExchanges: totalExchanges[0].count || 0, totalRefunded: totalRefunded[0].total || 0, todayReturns: todayReturns[0].count || 0 }); } catch(e) { res.json({ totalReturns: 0, totalExchanges: 0, totalRefunded: 0, todayReturns: 0 }); } });
app.get('/api/sales/search/:receiptNo', async (req, res) => { const [sale] = await pool.query("SELECT * FROM sales WHERE receiptNo = ?", [req.params.receiptNo]); if (sale.length) { const [items] = await pool.query("SELECT * FROM sale_items WHERE saleId = ?", [sale[0].id]); sale[0].items = items; res.json(sale[0]); } else { res.json({ error: 'Sale not found' }); } });

// PURCHASE ORDERS
app.get('/api/purchase-orders', async (req, res) => { const [pos] = await pool.query("SELECT * FROM purchase_orders ORDER BY date DESC"); for (let po of pos) { const [items] = await pool.query("SELECT * FROM po_items WHERE poId = ?", [po.id]); po.items = items; } res.json(pos); });
app.post('/api/purchase-orders', async (req, res) => { try { const d = req.body; const poNumber = 'PO-' + Date.now().toString(36).toUpperCase(); const [po] = await pool.query("INSERT INTO purchase_orders (poNumber, supplierName, supplierId, notes, total, createdBy, date) VALUES (?,?,?,?,?,?,NOW())", [poNumber, d.supplierName, d.supplierId||null, d.notes, d.total, d.createdBy]); const poId = po.insertId; if (d.items) { for (let i of d.items) { await pool.query("INSERT INTO po_items (poId, productName, brand, variant, quantity, unitPrice, sellingPrice, lastPrice, currentStock, discount, total) VALUES (?,?,?,?,?,?,?,?,?,?,?)", [poId, i.productName, i.brand||'', i.variant||'', i.quantity, i.unitPrice, i.sellingPrice||0, i.lastPrice||0, i.currentStock||0, i.discount||0, i.total]); } } logActivity(null, 'Admin', 'purchase_order', 'PO: ' + poNumber); res.json({ success: true, poNumber: poNumber }); } catch(e) { res.json({ success: false, message: e.message }); } });
app.put('/api/purchase-orders/:id/receive', async (req, res) => { const [po] = await pool.query("SELECT * FROM purchase_orders WHERE id = ?", [req.params.id]); if (!po.length) return res.json({ success: false }); const [items] = await pool.query("SELECT * FROM po_items WHERE poId = ?", [req.params.id]); for (let i of items) { const [p] = await pool.query("SELECT * FROM products WHERE name=? AND brand=? AND variant=? AND isActive=1", [i.productName, i.brand, i.variant]); if (p.length) await pool.query("UPDATE products SET stock = stock + ?, cost = ? WHERE id = ?", [i.quantity, i.unitPrice, p[0].id]); } await pool.query("UPDATE purchase_orders SET status = 'received', receivedDate = NOW() WHERE id = ?", [req.params.id]); logActivity(null, 'Admin', 'po_received', 'PO received: ' + po[0].poNumber); res.json({ success: true }); });
app.put('/api/purchase-orders/:id/update', async (req, res) => { try { const d = req.body; await pool.query("DELETE FROM po_items WHERE poId = ?", [req.params.id]); await pool.query("UPDATE purchase_orders SET supplierName=?, supplierId=?, notes=?, total=?, date=NOW() WHERE id=?", [d.supplierName, d.supplierId||null, d.notes, d.total, req.params.id]); if (d.items) { for (let i of d.items) { await pool.query("INSERT INTO po_items (poId, productName, brand, variant, quantity, unitPrice, sellingPrice, lastPrice, currentStock, discount, total) VALUES (?,?,?,?,?,?,?,?,?,?,?)", [req.params.id, i.productName, i.brand||'', i.variant||'', i.quantity, i.unitPrice, i.sellingPrice||0, i.lastPrice||0, i.currentStock||0, i.discount||0, i.total]); } } res.json({ success: true, message: 'PO updated' }); } catch(e) { res.json({ success: false, message: e.message }); } });

// M-PESA
app.get('/api/mpesa/config', async (req, res) => { const [c] = await pool.query("SELECT * FROM mpesa_config WHERE id=1"); const config = c[0] || {}; res.json({ tillNumber: config.tillNumber || '', shortCode: config.shortCode || '', environment: config.environment || 'sandbox', configured: !!(config.consumerKey && config.consumerSecret && config.passkey) }); });
app.put('/api/mpesa/config', async (req, res) => { const { consumerKey, consumerSecret, passkey, tillNumber, shortCode, environment } = req.body; await pool.query("UPDATE mpesa_config SET consumerKey=?, consumerSecret=?, passkey=?, tillNumber=?, shortCode=?, environment=? WHERE id=1", [consumerKey, consumerSecret, passkey, tillNumber, shortCode, environment||'sandbox']); res.json({ success: true }); });
app.post('/api/mpesa/till-payment', async (req, res) => { const { saleId, mpesaReceiptNumber, phoneNumber, amount } = req.body; await pool.query("INSERT INTO mpesa_transactions (transactionType, saleId, phoneNumber, amount, mpesaReceiptNumber, status, date) VALUES ('till_payment', ?, ?, ?, ?, 'completed', NOW())", [saleId, phoneNumber, amount, mpesaReceiptNumber]); if (saleId) await pool.query("UPDATE sales SET paymentMethod='M-Pesa', mpesaRef=? WHERE id=?", [mpesaReceiptNumber, saleId]); res.json({ success: true }); });
app.get('/api/mpesa/transactions', async (req, res) => { const [r] = await pool.query("SELECT * FROM mpesa_transactions ORDER BY date DESC LIMIT 100"); res.json(r); });
app.get('/api/mpesa/transaction/:checkoutRequestID', async (req, res) => { const [r] = await pool.query("SELECT * FROM mpesa_transactions WHERE checkoutRequestID=?", [req.params.checkoutRequestID]); res.json(r[0] || { status: 'not_found' }); });

// CREDIT CUSTOMERS
app.get('/api/credit-customers', async (req, res) => { const [r] = await pool.query("SELECT * FROM credit_customers WHERE isActive=1 ORDER BY name"); res.json(r); });
app.get('/api/credit-customers/:id', async (req, res) => { const [c] = await pool.query("SELECT * FROM credit_customers WHERE id=?", [req.params.id]); if (c.length) { const [sales] = await pool.query("SELECT * FROM credit_sales WHERE customerId=? ORDER BY date DESC LIMIT 10", [req.params.id]); const [payments] = await pool.query("SELECT * FROM debt_payments WHERE customerId=? ORDER BY date DESC LIMIT 10", [req.params.id]); c[0].recentSales = sales; c[0].payments = payments; } res.json(c[0] || {}); });
app.post('/api/credit-customers', async (req, res) => { const { name, phone, idNumber, address, debtLimit, cashierId, cashierName } = req.body; const [r] = await pool.query("INSERT INTO credit_customers (name, phone, idNumber, address, debtLimit, registeredBy, registeredById, dateRegistered) VALUES (?,?,?,?,?,?,?,NOW())", [name, phone, idNumber, address, debtLimit||5000, cashierName||'Admin', cashierId||null]); res.json({ success: true, id: r.insertId }); });
app.put('/api/credit-customers/:id', async (req, res) => { const { name, phone, idNumber, address, debtLimit, isActive } = req.body; await pool.query("UPDATE credit_customers SET name=?, phone=?, idNumber=?, address=?, debtLimit=? WHERE id=?", [name, phone, idNumber, address, debtLimit, req.params.id]); if (isActive !== undefined) await pool.query("UPDATE credit_customers SET isActive=? WHERE id=?", [isActive, req.params.id]); res.json({ success: true }); });
app.get('/api/credit-customers/search/:query', async (req, res) => { const q = '%' + req.params.query + '%'; const [r] = await pool.query("SELECT * FROM credit_customers WHERE isActive=1 AND (name LIKE ? OR phone LIKE ? OR idNumber LIKE ?) LIMIT 10", [q, q, q]); res.json(r); });

// DEBT PAYMENTS
app.post('/api/debt-payments', async (req, res) => { const { customerId, customerName, amount, paymentMethod, receivedBy, receivedById } = req.body; await pool.query("INSERT INTO debt_payments (customerId, customerName, amount, paymentMethod, receivedBy, receivedById, date) VALUES (?,?,?,?,?,?,NOW())", [customerId, customerName, amount, paymentMethod||'cash', receivedBy, receivedById]); await pool.query("UPDATE credit_customers SET totalDebt = GREATEST(0, totalDebt - ?) WHERE id = ?", [amount, customerId]); res.json({ success: true }); });
app.get('/api/debt-payments/:customerId', async (req, res) => { const [r] = await pool.query("SELECT * FROM debt_payments WHERE customerId=? ORDER BY date DESC", [req.params.customerId]); res.json(r); });
app.delete('/api/debt-payments/:id', async (req, res) => { try { const [payment] = await pool.query("SELECT * FROM debt_payments WHERE id = ?", [req.params.id]); if (!payment.length) return res.json({ success: false }); await pool.query("UPDATE credit_customers SET totalDebt = totalDebt + ? WHERE id = ?", [payment[0].amount, payment[0].customerId]); await pool.query("DELETE FROM debt_payments WHERE id = ?", [req.params.id]); logActivity(null, 'Admin', 'delete_payment', 'Deleted payment: ' + payment[0].customerName + ' - KES ' + Number(payment[0].amount).toLocaleString()); res.json({ success: true }); } catch(e) { res.json({ success: false, message: e.message }); } });

// CREDIT SALES
app.post('/api/credit-sales', async (req, res) => { const { saleId, customerId, customerName, amount, cashierId, cashierName } = req.body; const [c] = await pool.query("SELECT * FROM credit_customers WHERE id=?", [customerId]); if (!c.length) return res.json({ success: false }); const debtBefore = Number(c[0].totalDebt); const debtAfter = debtBefore + amount; if (debtAfter > c[0].debtLimit) return res.json({ success: false, message: 'Debt limit exceeded!' }); await pool.query("INSERT INTO credit_sales (saleId, customerId, customerName, amount, debtBefore, debtAfter, cashierId, cashierName, date) VALUES (?,?,?,?,?,?,?,?,NOW())", [saleId, customerId, customerName, amount, debtBefore, debtAfter, cashierId, cashierName]); await pool.query("UPDATE credit_customers SET totalDebt = totalDebt + ? WHERE id = ?", [amount, customerId]); await pool.query("UPDATE sales SET isCredit=1, customerId=? WHERE id=?", [customerId, saleId]); res.json({ success: true, debtBefore, debtAfter }); });
app.get('/api/credit-sales', async (req, res) => { const [r] = await pool.query("SELECT * FROM credit_sales ORDER BY date DESC LIMIT 100"); res.json(r); });
app.get('/api/credit-summary', async (req, res) => { const [td] = await pool.query("SELECT SUM(totalDebt) as total FROM credit_customers WHERE isActive=1"); const [ac] = await pool.query("SELECT COUNT(*) as count FROM credit_customers WHERE isActive=1 AND totalDebt > 0"); const today = new Date().toISOString().split('T')[0] + '%'; const [ts] = await pool.query("SELECT SUM(amount) as total FROM credit_sales WHERE date LIKE ?", [today]); const [tp] = await pool.query("SELECT SUM(amount) as total FROM debt_payments WHERE date LIKE ?", [today]); res.json({ totalDebt: Number(td[0].total||0), activeCustomers: ac[0].count, todayCreditSales: Number(ts[0].total||0), todayPayments: Number(tp[0].total||0) }); });

// DAILY REPORTS
app.get('/api/daily-reports', async (req, res) => { const [r] = await pool.query("SELECT * FROM daily_reports ORDER BY reportDate DESC LIMIT 30"); res.json(r); });
app.get('/api/daily-reports/today', async (req, res) => { var today = new Date().toISOString().split('T')[0]; var [report] = await pool.query("SELECT * FROM daily_reports WHERE reportDate = ?", [today]); if (!report.length) { var [sales] = await pool.query("SELECT * FROM sales WHERE date LIKE ? AND isVoid=0", [today + '%']); var [itemsSold] = await pool.query("SELECT SUM(si.quantity) as total FROM sale_items si JOIN sales s ON si.saleId=s.id WHERE s.date LIKE ? AND s.isVoid=0", [today + '%']); var [stockAdded] = await pool.query("SELECT SUM(pi.quantity) as total FROM po_items pi JOIN purchase_orders po ON pi.poId=po.id WHERE po.receivedDate LIKE ?", [today + '%']); var [stockSold] = await pool.query("SELECT SUM(si.quantity) as total FROM sale_items si JOIN sales s ON si.saleId=s.id WHERE s.date LIKE ? AND s.isVoid=0", [today + '%']); var [products] = await pool.query("SELECT COUNT(*) as count, SUM(stock) as totalStock FROM products WHERE isActive=1"); var totalSales = sales.reduce(function(s, sale) { return Number(s) + Number(sale.total||0); }, 0); await pool.query("INSERT INTO daily_reports (reportDate, totalSales, transactionCount, totalItemsSold, closingStock, stockAdded, stockSold, productsCount) VALUES (?,?,?,?,?,?,?,?)", [today, totalSales, sales.length, itemsSold[0]?.total||0, products[0]?.totalStock||0, stockAdded[0]?.total||0, stockSold[0]?.total||0, products[0]?.count||0]); var [newReport] = await pool.query("SELECT * FROM daily_reports WHERE reportDate = ?", [today]); report = newReport; } res.json(report[0] || {}); });
app.post('/api/daily-reports/generate', async (req, res) => { var today = new Date().toISOString().split('T')[0]; var [sales] = await pool.query("SELECT * FROM sales WHERE date LIKE ? AND isVoid=0", [today + '%']); var [itemsSold] = await pool.query("SELECT SUM(si.quantity) as total FROM sale_items si JOIN sales s ON si.saleId=s.id WHERE s.date LIKE ? AND s.isVoid=0", [today + '%']); var [stockAdded] = await pool.query("SELECT SUM(pi.quantity) as total FROM po_items pi JOIN purchase_orders po ON pi.poId=po.id WHERE po.receivedDate LIKE ?", [today + '%']); var [stockSold] = await pool.query("SELECT SUM(si.quantity) as total FROM sale_items si JOIN sales s ON si.saleId=s.id WHERE s.date LIKE ? AND s.isVoid=0", [today + '%']); var [products] = await pool.query("SELECT COUNT(*) as count, SUM(stock) as totalStock FROM products WHERE isActive=1"); var totalSales = sales.reduce(function(s, sale) { return Number(s) + Number(sale.total||0); }, 0); await pool.query("INSERT INTO daily_reports (reportDate, totalSales, transactionCount, totalItemsSold, closingStock, stockAdded, stockSold, productsCount) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE totalSales=?, transactionCount=?, totalItemsSold=?, closingStock=?, stockAdded=?, stockSold=?, productsCount=?", [today, totalSales, sales.length, itemsSold[0]?.total||0, products[0]?.totalStock||0, stockAdded[0]?.total||0, stockSold[0]?.total||0, products[0]?.count||0, totalSales, sales.length, itemsSold[0]?.total||0, products[0]?.totalStock||0, stockAdded[0]?.total||0, stockSold[0]?.total||0, products[0]?.count||0]); res.json({ success: true }); });

app.all('/{*splat}', (req, res) => { res.sendFile(path.join(__dirname, 'frontend', 'public', 'index.html')); });

initDB().then(() => {
    app.listen(PORT, '0.0.0.0', () => { 
        console.log('========================================');
        console.log('  TALAEN HARDWARE SYSTEM');
        console.log('  Server: http://localhost:' + PORT);
        console.log('  Network: http://YOUR-IP:' + PORT);
        console.log('========================================');
    });
}).catch(err => { console.error('DB init error:', err); });
